Repository Arminek/1000CardGame, pull requests merged in 2020-11, with the labels that each got.

#59 [Infrastructure] Configure k8s deployment
  server/helm/.helmignore
  server/helm/Chart.yaml
  server/helm/templates/_helpers.tpl
  server/helm/templates/deployment.yaml
  server/helm/templates/hpa.yaml
  server/helm/templates/ingress.yaml
  server/helm/templates/service.yaml
  server/helm/templates/serviceaccount.yaml
  server/helm/templates/tests/test-connection.yaml
  server/helm/values.yaml
  server/src/main/kotlin/com/rocketarminek/thousandcardgame/server/game/infrastructure/controller/HealthAction.kt
Labels: backend

#60 [Infrastructure] Manually switch image version
  server/helm/Chart.yaml
  server/helm/templates/deployment.yaml
  server/src/main/kotlin/com/rocketarminek/thousandcardgame/server/game/infrastructure/controller/HealthAction.kt
Labels: backend

#61 Feature/prepare docker image
  client/Dockerfile
  client/nginx-custom.conf
  client/src/app/facades/game.facade.ts
  client/src/app/services/game.service.ts
  client/src/environments/environment.prod.ts
  client/src/environments/environment.ts
Labels: backend, frontend

#62 [Infrastructure] Create k8s deployment
  client/helm/.helmignore
  client/helm/Chart.yaml
  client/helm/templates/_helpers.tpl
  client/helm/templates/deployment.yaml
  client/helm/templates/hpa.yaml
  client/helm/templates/ingress.yaml
  client/helm/templates/service.yaml
  client/helm/templates/serviceaccount.yaml
  client/helm/templates/tests/test-connection.yaml
  client/helm/values.yaml
Labels: backend, frontend

#65 feature-menu fix footer and glow effect
  client/src/app/menu/components/menu/menu.component.scss
Labels: frontend

#66 feature-menu styling update
  client/src/app/app.component.html
  client/src/app/app.component.scss
Labels: frontend
